specVersion: 0.2.0
name: zenlink-bifrost-subql
version: 1.0.0
description: ''
repository: 'https://github.com/Hayden0323/subql-demo'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://bifrost-parachain.api.onfinality.io/public-ws'
  genesisHash: '0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
